src/parse_stream.jl
src/token_kinds.jl
src/tokens.jl

Make is_error and K"" macro consistent with new lexer error kinds

---

src/diagnostics.jl
src/parse_stream.jl
src/syntax_tree.jl
src/utils.jl

* Update `_printstyled` to support foreground colors
* Minor docs update for `bump()`

Some minor cleanups

---

README.md

@benchung I added some questions you've had about concatenation to the docs here

Docs: Add notes about concatenation AST forms

---

README.md
src/parser.jl
test/parser.jl

Fixes https://github.com/JuliaLang/JuliaSyntax.jl/issues/79.

Correctly handle begin as kw in typed comprehension

---

src/parser.jl

* Eliminate the use of Ref to communicate values out of the anonymous function passed to parse_brackets(). It seems this forces unnecessary allocation of the Ref captured by the closure.
* Force specialization on `down` in `parse_assignment_with_initial_ex` to avoid an unnecessary generic dispatch there.
This should probably bring down the total number of allocations during parsing to around O(log(N) + M) in the length of the file N and depth, M, of the AST.

Remove many unnecessary allocations

---

Project.toml
README.md

Probably a good time for 0.2, now that this package works with REPL completion given #102

Fix project status in README + bump to 0.2

---

src/expr.jl
src/kinds.jl
src/parse_stream.jl
src/parser.jl
test/parser.jl

A flag is a waste for this; we can just use a different kind for this horrible edge case.
Small part of addressing #113

Remove TRY_CATCH_FINALLY_FLAG

---

README.md

Add docs on how to use JuliaSyntax inside VSCode

---

src/tokenize.jl
test/tokenize.jl

Fix tokenization of `1.#`

---

test/expr.jl

Fix dotcall tests

---

src/tokenize.jl
test/tokenize.jl

Fix https://github.com/JuliaLang/JuliaSyntax.jl/issues/170

Fix for tokenization of consecutive nested multiline comments

---

src/expr.jl
test/expr.jl

Fix = to kw conversion in `x[a, b; i=j]`

---

src/parser.jl
test/parser.jl

Allow operator-named macros to be used without spaces.
Part of #134

Fix for operator-named macros: parse `@+x` as `@+ x`

---

test/parse_packages.jl
test/test_utils.jl

The only weird case here is Base's test/syntax.jl which contains some pretty weird syntax cases. Cases where we don't really want to parse the same...

Enable parsing of Base tests

---

src/syntax_tree.jl
test/syntax_tree.jl

These add a couple more convenience methods useful for TypedSyntax.

AbstractSyntaxNode generalization & convenience

---

src/hooks.jl
src/parser_api.jl
src/utils.jl
test/benchmark.jl

* Basic benchmark script. Not connected to anything yet
* Document the `ignore_errors` flag
* Move `fl_parse` related Base hooks into hooks.jl

Add basic benchmark script + other rearrangments

---

src/literal_parsing.jl
src/parse_stream.jl
test/diagnostics.jl
test/parser_api.jl

fix lexing `'\\` to not error in the validate token step

---

README.md

Copy this list from issue #88 to the docs.

Big list of AST difference between Expr & GreenNode

---

src/parse_stream.jl
src/parser.jl
test/parser.jl

Discovered parsing packages in General (NDTensors in particular)

Fix for detecting call heads in function signatures

---

src/expr.jl

avoid a runtime dispatch when converting to expr

---

src/hooks.jl
src/source_files.jl
test/hooks.jl

Support for lineno in core parser hooks

---

src/hooks.jl
test/hooks.jl

Fixes for `Expr(:incomplete)` detection

---

src/parser.jl
test/diagnostics.jl

Improve error message for closing tokens in parse_atom

---

src/green_tree.jl
test/green_node.jl
test/runtests.jl
test/test_utils.jl

Also add some more direct GreeNode tests

== operator for green trees

---

src/literal_parsing.jl
test/literal_parsing.jl

See upstream PR https://github.com/JuliaLang/julia/pull/49559

Normalize ℏ (\hslash) to ħ (\hbar)

---

.github/workflows/CI.yml
src/syntax_tree.jl

Small fix to make JuliaSyntax work when Int === Int32

---

docs/make.jl
docs/src/api.md
src/parse_stream.jl
src/source_files.jl
src/syntax_tree.jl

Add a few missing docstrings for API docs

---

src/source_files.jl
test/source_files.jl

Fixes one part of the error found in #375

Fix highlighting of ranges which start with non-ascii chars
