JuliaLang/JuliaSyntax.jl

src/parser.jl, test/parser.jl
What's still missing here is the correct compat check, since this is
only supported in Julia 1.8. I wasn't sure how to check for this in
`check_ncat_compat`.
=> add support for empty nd-array syntax

src/green_tree.jl, src/parse_stream.jl, src/parser.jl, src/tokens.jl, test/parser.jl
* Dectect whether array concatenation is either column-major or
row-major in the first and second dimesions. Report errors for mixed
orderings.
* Treat ;; as line continuation when used in hcat
* Treat newlines as insignificant when mixed with semicolons as
separators.
=> Fixes for `;;` and spaces in array concatenation

README.md, src/syntax_tree.jl, test/parse_packages.jl, test/syntax_tree.jl
The following construct is parsed oddly by the reference parser with the
tuple omitted from the argument list. Add a compatibility hack for that
during Expr conversion.
```julia
function (xs...)
body
end
```
With this we now have compatible parsing for all of the stdlib, so turn
on this test by default.
=> Compat for odd Exprs in long form anonymous functions

src/parser.jl, test/parse_packages.jl, test/test_utils.jl
It turns out that SparseArrays has some unused .jl files in the tests
with broken syntax in 1.8 dev. Fix the JuliaSyntax parser comparison
tool to ignore these cases.
=> Fix parser comparison tool. stdlib now parses for 1.6 - 1.8

Tokenize/src/lexer.jl, Tokenize/test/lexer.jl, src/parser.jl, test/parser.jl
This fixes dedenting of raw triple quoted strings where a backslash immediately precedes the newline.
=> Fix raw triple string dedenting with `\` before newline

src/hooks.jl, src/parser.jl, test/hooks.jl, test/runtests.jl
* Make ParseError work with Meta.parse()
* Make incremental parsing of statements work
* Add some basic tests
Fixes #8
=> Improvements to core parsing hooks

Tokenize/src/lexer.jl, Tokenize/src/token.jl, Tokenize/src/token_kinds.jl, src/green_tree.jl, src/parse_stream.jl, src/parser.jl, src/parser_api.jl, src/syntax_tree.jl, test/parse_stream.jl
This is a series of cleanup/optimization commits which
* Reduce the size of data structures in `ParseStream`
* Fix various JET warnings, particularly removing boxed closure captures and fixes to `EMPTY_TOKEN` in Tokenize
* Pool and reuse some data structures during parsing
* Better kind()/flags() API + compactify SyntaxToken flags
* Remove need for storing newline flag on SyntaxToken
=> Optimization and cleanup in parse stream

src/green_tree.jl, src/parse_stream.jl, src/parser.jl, src/parser_api.jl, test/parser_api.jl, test/test_utils.jl
This data rearrangement gives a cleaner separation between tokens (which
keep track of bytes in the source text) vs internal tree nodes (which
keep track of which tokens they cover). As a result it reduces the size
of the intermediate data structures.
As part of rewriting build_tree to use the new data structures it's also
become much faster and building the green tree no longer dominates the
parsing time (probably due to fixing some type stability issues).
With this change we're around 14x the speed of the flisp parser in producing
the green tree, and about 6x faster in producing `Expr` data structures.
=> Separate token output from internal nodes in ParseStream

README.md, Tokenize/benchmark/lex_base.jl, Tokenize/src/lexer.jl, Tokenize/src/token.jl, Tokenize/src/token_kinds.jl, Tokenize/test/lexer.jl, src/parse_stream.jl, src/tokens.jl
It is very rare for tokens to be errors but we still need to pay the cost of the `TokenError` field every time. This PR just moves the `TokenError` into a `Kind` and has a function `iserror` to check if the kind is of an error type.
Made on top of https://github.com/c42f/JuliaSyntax.jl/pull/16
=> get rid of the `TokenError` field in `Token`

src/parse_stream.jl, src/parser_api.jl
While a bit counter-intuitive, this enables us to use an initial
sentinel token for recording the first byte of the first real token
which removes a bunch of special case hacks for computing the last byte
of the current output token.
=> Cleanup: put next_byte in token rather than first_byte

Tokenize/src/lexer.jl, Tokenize/test/lexer.jl
Fixes #23
Ported from https://github.com/JuliaLang/Tokenize.jl/pull/197, thanks to @pfitzseb :-)
=> Treat UTF-8 BOM as whitespace

Tokenize/src/lexer.jl, Tokenize/src/utilities.jl, Tokenize/test/lexer.jl
Fixes https://github.com/JuliaLang/JuliaSyntax.jl/issues/31.
=> Fix some dotop tokenization issues

src/parser.jl, test/parser.jl, test/test_utils.jl
The `)` was attached to the `parameters` expression, but should be attached to node along with the opening `(` instead.
Also avoid a duplicate diagnostic messages for closing brackets
=> Improve trivia attachment for `)` in parse_brackets

sysimage/JuliaSyntaxCore/Project.toml, sysimage/compile.jl
This allows us to use JuliaSyntax baked into the sysimage to develop
a separate JuliaSyntax with Revise :-D
=> Separate UUID for the JuliaSyntax in sysimage

src/hooks.jl, src/parse_stream.jl, sysimage/compile.jl
* Fix copying of Tokenize source (clash with refactoring in #40)
* Ensure the previous default parser is restored by `enable_in_core!()`. This could be other than Core.Compiler.fl_parse if we're using JuliaSyntax.jl to develop itself :)
=> Fixes for JuliaSyntax in Core / sysimage

src/hooks.jl, test/hooks.jl
core_parser_hook() should return `nothing` when attempting to parse
statements or atoms, but when there's nothing but whitespace remaining.
=> Fix core hook when parsing only whitespace.

src/parser.jl, test/parser.jl, test/test_utils.jl
If a closing token is found in parse_atom, we still need to emit a
nontrivia token to make the resulting parse tree consistent. We choose
an invisible token for this.
Also add various minor fixes to error recovory and a few additional
tests in parse_atom and elsewhere.
Fixes #43
=> Bugfix: Always emit a token from parse_atom

src/hooks.jl, test/hooks.jl
Previously, `Meta.parseatom()` would consume trailing whitespace which breaks usages like in `Base.parse_shell()`
=> Fix hooks: whitespace parsing with Meta.parseatom()

src/hooks.jl
* Freeze world age by default in enable_in_core!()
* Use a `Ref` to hide the invocation of the main hook function from the compiler
I don't understand why the use of the `Ref` (the second commit) seems necessary here; I would have thought that `invoke_in_world` should have done the job. But when I tested on Julia 1.7.3 without the `Ref`, loading the `TerminalLoggers` package caused significant latency on the next parse time.
Presumably the `Ref` breaks some extra backedges, though I'm not sure what they are or how best to debug the situation. (Perhaps `SnoopCompile`? I'd need to learn how to use that tooling.)
=> Reduce invalidation/recompliation for parser usage in sysimage

src/hooks.jl, sysimage/JuliaSyntaxCore/src/JuliaSyntaxCore.jl
Move the hacky code for overriding Core._parse from the sysimage
init module into JuliaSyntax.jl proper, to allow it to be reused as
necessary.
=> Make enable_in_core! safe for use in precompilation

src/hooks.jl
* Use `Core.set_parser` rather than eval if it's available (see https://github.com/JuliaLang/julia/pull/46372)
* Minor cleanup to inference barrier in `core_parser_hook`
=> Minor cleanups to core parser hook

src/hooks.jl, src/utils.jl, test/test_utils.jl, test/tokenize.jl
This allows us to call the flisp parser directly instead of using
`Meta.parse` which may have been overridden with the JuliaSyntax parser.
Fix the tests to always use the flisp reference parser.
=> Add fl_parse() test tool to call flisp parser directly

src/parser.jl, src/syntax_tree.jl, test/parser.jl
Fixes https://github.com/JuliaLang/JuliaSyntax.jl/issues/59.
=> Fix vect parsing with newline before comma

tools/check_all_packages.jl
I ran this with https://github.com/JuliaLang/JuliaSyntax.jl/pull/60 and ended up with
```
152900 files parsed
37 failures
0.82ms per file, 126s in total
```
Issues are open for most of those failures.
=> Add check_all_packages script

src/parser.jl, test/parser.jl
`-2` is numeric literal `-2`, but ensure `.-2` should be `(call .- 2)`
Fixes #63
=> Fix: .- and .+ before numeric literals

src/parser.jl, test/parser.jl
This won't be valid syntax during lowering, but the parser shouldn't
throw.
Also a little cleanup to clarify variable naming while we're here.
Fixes #53
=> Fix parser crash for empty tuple parsing in parse_function

src/parser.jl, test/parser.jl
Fixes https://github.com/JuliaLang/JuliaSyntax.jl/issues/66.
=> Fix early-abort handling in array_parse

src/parser.jl, src/utils.jl, src/value_parsing.jl, test/parser.jl, test/value_parsing.jl
It seems we can't use Base.parse for floats because this disallows
underflow. So replicate the logic of it here in julia-level code and allow
`errno=ERANGE` in the underflow case.
This implementation is still somewhat (~15%) slower than Base.parse for some reason.
Should fix #65
TODO:
=> Fix over/underflow in parsing float literals

src/expr.jl, src/parser.jl, test/parser.jl
This allows `a ? b : c` syntax to be clearly distinguished from normal
`if a b else c end` without reparsing syntax trivia.
For compatibility we convert to `:if` for normal `Expr`
=> Use `K"?"` for head of ternary conditional

README.md, src/parser.jl, test/parser.jl
* More notes about where AST forms differ
* Minor fix to test case comment + unify recovery for parsing `:` noticed while writing the docs
=> Add notes about AST differences + minor recovery fix

README.md, src/expr.jl, src/kinds.jl, src/parser.jl, test/expr.jl, test/parser.jl
Ensures that strings are always encapsulated within a
`string` internal node of the parse tree, giving a place to include the
delimiters and unifying interpolated strings / strings with internal
whitespace with plain string literals.
~~Also, wrap `K"$"` nodes around interpolations in strings~~ - update: removed this part
That is, parse
`"a $x b"`
as
`(string "a " ($ x) " b")`
This makes the presence of interpolation syntax explicit, just as it is
for interpolation into expression literals.
There's two advantages of this
* We don't need a hack to distinguish "$("str")" from "str". This seems
necessary now that all strings are wrapped in K"string" nodes, as the
older hack doesn't work (hmm on second thoughts ... I think?)
* The `$` node gives a place to attach delimiter trivia, which makes …
=> Always use string nodes wrapping string chunks

README.md
Update link to last known work on the lowerer that was proposed but not merged AFAIK in Julia circa 2019
The branch was deleted and no direct link is available anymore .
This one should be the last and most complete ref about it
=> Update link to last known work on the lowerer

README.md, src/expr.jl, src/parser.jl, test/parser.jl
The reference parser represents `do` syntax with a closure for the second
argument. That is,
```julia
f(x) do y
body
end
```
becomes `(do (call f x) (-> (tuple y) (block body)))` in the reference parser.
However, the nested closure with `->` head is implied here rather than present
in the surface syntax, which suggests this is a premature desugaring step.
Instead this PR changes things to emit the flatter structure `(do (call f x) (tuple y) (block body))`.
Discussed with @JeffBezanson today on a call.
Part of #88
=> Parse `do` syntax without desugaring the closure

Project.toml, src/JuliaSyntax.jl, src/parse_stream.jl
We can use Mmap for mapping IOStream but
* It's not clear that this is necessary
* Removing it avoids stdlib dependencies, making Base integration easier.
=> Remove Mmap as a dependency

src/hooks.jl, src/tokenize.jl, test/tokenize.jl
* Bugfix in character offsets in Lexer
* Fix calling of `fl_parse` in Julia 1.8 when `JuliaSyntax.parse` fails
=> Some minor fixes

src/hooks.jl, src/parser_api.jl, src/syntax_tree.jl, test/hooks.jl
This allows REPL completion to work correctly. It works by pattern matching the parse tree, rather than hard coding incomplete expression detection into the parser itself.
This took a while because I got distracted with #88. Though doing some of those things first helped make this quite a lot cleaner. There's still more changes from #88 which would help make this nicer but for now it works.
The tests here are somewhat derived from `Base`, but I had to review them all (ie the tests pasted in https://github.com/JuliaLang/JuliaSyntax.jl/pull/71#issuecomment-1225364445) because they turn out to not really make sense.  For example, `"begin;"` and `"begin"` are both the prefix of a block construct, one of them shouldn't come out as `:other`.
Alternative to #71, CC @aviatesk :-)
Fix #42, would …
=> Generate `Expr(:incomplete)`

src/expr.jl, src/kinds.jl, src/parser.jl, test/expr.jl, test/parser.jl
For Expr there's various cases where = is parsed into a kw head, but this is inconsistent especially when named tuples come into play. That is, the `=` parses to different heads:
* as `=`  in `(a=1, b=2)`
* as `kw` in `f(a=1, b=2)`
This causes extra complexity in the parser, and is visually confusing for macro writers. Instead, this change always parses `=` to the K"=" head, converting to the :kw head when lowering to Expr.
This all seems to work fairly well, with one fairly obscure but awkward exception - in infix notation such as `(x = 1) != y` the `=` is assignment, not a keyword argument.
Close #99
=> Parse keyword args with `=` head rather than `kw`

src/hooks.jl, src/parser.jl, test/parser.jl
=> Stricter parsing of exception names in `catch $excname`

README.md, src/hooks.jl, src/parse_stream.jl, src/parser_api.jl, test/expr.jl, test/parse_stream.jl, test/parser_api.jl, test/test_utils.jl
`JuliaSyntax.parse()` and `JuliaSyntax.parseall()` were generally pretty inconvenient to use.
This change reworks what I had called `parseall()` to be more similar to `Meta.parse()` and adds `parseall()` and `parseatom()` in analogy to the `Base.Meta` versions of these functions.
The lower level function `parse!()` is provided to work with `ParseStream` for cases where more control is required.
=> Rework `JuliaSyntax.parse()` public API

src/parser_api.jl, sysimage/precompile.jl, sysimage/precompile_exec.jl, test/parser.jl, test/test_utils.jl
Required for better integration in https://github.com/JuliaLang/julia/pull/46372
=> Tweaks to allow vendoring into Base

README.md, src/expr.jl, src/hooks.jl, src/kinds.jl, src/parser.jl, src/syntax_tree.jl, src/tokenize.jl, test/expr.jl, test/parser.jl, test/tokenize.jl
Here we split off char delimiters in the tokenizer rather than re-parsing them later during value conversion. Also add a K"char" internal node to cover the delimiters and the literal char content in the green tree.
This allows us to remove another special case token error kind (ErrorEofChar) and makes char representation in the tree similar to string representation.
Part of #88 and helps with #110
=> Split char delimiters early and emit K"char" node

src/expr.jl, src/parse_stream.jl, src/parser.jl, src/tokenize.jl, test/parser.jl
We now record which precise call syntax was used out of the four options:
* Prefix calls with parens
* Prefix operator calls
* Infix operator calls
* Postfix operator calls
This allows us to distinguish keyword arguments from assignment, fixing several bugs with = to kw conversion.
Fixes #113 
Close #99
=> Record fixity of call type in flags

src/parser.jl, test/parser.jl
Ensure things like `@S[a,b]` where there's no whitespace between the `@S` and
opening `[` are parsed correctly.
=> Bug fix for macro call square bracket whitespace

src/expr.jl, src/parser.jl, test/parser.jl
This moves the unnecessary special cases for lists of bindings in `let` out of the parser and into Expr lowering.
Part of #88
=> Always emit a block for `let` binding lists

src/expr.jl, src/parser.jl, test/parser.jl
Here I've replicated the fix from JuliaLang/julia#45024 so that `const x` (ie, without an assignment) is only valid within a `struct` and is otherwise an error.
Also avoid lowering the syntax `global const` into `const global` within the parser; do this in Expr conversion instead. This more closely reflects the structure of the source, allowing trivia attachment to be more natural. Part of #88
Fix #129.
=> Fix const struct field errors + cleanup `global const` AST

src/kinds.jl, src/parse_stream.jl, src/parser.jl, test/parse_stream.jl, test/parser.jl, test/test_utils.jl
This permits the extra parentheses in things like
function (funcname(some, long, argument, list)
where {Type,Params})
body
end
This syntax "works" in the reference parser and has been seen in the wild so we need to support it for compatibility. (However, it's broken when combined with return type annotations which suggests it's more a syntactic aberration rather than an intentional feature.)
Fix #116
=> Permit parens in function call signatures

src/expr.jl, src/parser.jl, test/parser.jl
Useful to hold associated trivia (delimiter and var prefix) and indicate in a clean way that `var""` was used.
Part of #88
=> Wrap `var""` nonstandard identifiers in var nodes

src/expr.jl, src/parser.jl, test/parser.jl
Here we emit `(a, b; c, d; e, f)` as
(tuple a b (parameters c d) (parameters e f))
which should make these simpler to process, rather than using the nested form
(tuple a b (parameters c d parameters e f)))
Part of #88
=> More flattened form for multiple frakentuple parameters

src/parser.jl, test/parser.jl
Failure due to overeager error detection of `end` keyword.
Part of #134
CC @pfitzseb
=> Fix for parsing `end` in `A[x ? y : end]`

src/parser.jl, test/parser.jl
In space sensitive contexts, `~` is parsed as unary or binary depending on whitespace to the left and right of the `~`. In this case it should be binary and parse as `(ref (call-i ~ a b))`
=> Fix parsing of `[a~b]`

src/tokenize.jl, test/tokenize.jl
* `.1..` is `.1` followed by `..`
* `0x01..` is `0x01` followed by `..`
Also fixes these cases when followed by `...`
Part of #134
=> Fix tokenization of numbers followed by `..`

src/parser.jl, test/parser.jl
Correctly parse dots and other same-precedence chaining after macro calls:
@A().x
@A{a}.x
@A[a].x
Also allow general forms in macro paths, such as calls:
f().@x
This is allowed by the reference parser but seemed weird so it was disallowed here. But it turns out this doesn't prevent computed macro paths as the A in `A.@x` is looked up dynamically - so just simplify things and allow this.
Fixes two parts of #134
=> Fixes for macro paths and call chain parsing

src/expr.jl, src/kinds.jl, src/parser.jl, src/syntax_tree.jl, test/parser.jl
The reason to use `__dot__` is to allow `macro __dot__` to be defined in normal Julia source. But doing this in the parser is an awkward special case - better to do it later during some lowering step.  Here done in `Expr` conversion.
=> Lower `@ .` to `@ __dot__` not in parser but in `Expr` conversion

src/hooks.jl, src/parser.jl, test/parser.jl
This change prevents a crash for various cases of bad syntax involving macro names. In particular things like `@[x] a` and `@A.x a`.
The latter case where the @ is separated from the actual macro name is a pain to deal with and is only approximately correct in this PR. But I'm not sure why we even support this syntax and maybe we could warn about it or deprecate it. So unclear whether going to greater lengths emitting K"TOMBSTONE" to be precise about error reporting in that case is worth it.
=> Report bad macro names more clearly

src/diagnostics.jl, src/hooks.jl, src/kinds.jl, src/parse_stream.jl, src/parser.jl, src/parser_api.jl, src/syntax_tree.jl, src/tokenize.jl, src/value_parsing.jl, test/diagnostics.jl, test/parser.jl, test/runtests.jl, test/test_utils.jl, test/tokenize.jl, test/value_parsing.jl
Here we unconditionally validate all literals after `parse!()` - this includes processing String and Char escape sequences, and detecting numeric overflow.
Currently the way this is done up front in `parse!()` means it'll be redone later during conversion to SyntaxNode. The time cost of this in parsing to Expr seems to be about 20% in the worst case where the code consists of a large array of Float64 literals. Which isn't great but is probably acceptable.  (This rework can be avoided with extra refactoring, but requires a place to put the parsed literals and a way to recover them during tree building. Those things can probably be done in a later follow up.)
fix #138
fix #109 
fix #82 
fix #67
=> Validate literals at parse time

src/expr.jl, src/kinds.jl, src/parse_stream.jl, src/parser.jl, test/expr.jl, test/parser.jl
Dotted call syntax parses into various forms which aren't really consistent. Especially, Expr is inconsistent about dotted infix calls vs dotted prefix calls. In this change we adopt a more consistent (and hopefully less mysterious!) parsing where dotted calls get their own `dotcall` head which is otherwise like the `call` head:
f.(a, b)  ==>  (dotcall f a b)
a .+ b    ==>  (dotcall-i a + b)
.+ b      ==>  (dotcall-pre + b)
In other cases where a dotted operator appears as an atom we split the dot from an operator, so `.+` becomes `(. +)`. Thus, for comparison chains and prefix calls, we have the following parsings:
a .< b < c  ==>  (comparison a (. <) b < c)
.*(a,b)     ==>  (call (. *) a b)
TODO: Unambiguously reconstructing the associated Expr in the latter cases is more challenging …
=> Parse dotted calls with `dotcall` head

src/parser_api.jl, test/parser_api.jl
This allows extracting the recovered tree (containing error nodes) without using the low-level parse!() API.
=> Add ignore_errors keyword to main parser API

src/parse_stream.jl, test/diagnostics.jl
`jl_strtod_c` can return "underflow" even for valid cases such as `5e-324` where the source string is parsed to an exact Float64 representation.
So we can't rely on jl_strtod_c to detect "invalid" underflow. Rather, only warn when underflowing to zero which is probably a programming mistake.
=> Only warn when float literals underflow to zero

src/source_files.jl, test/runtests.jl, test/source_files.jl, test/test_utils.jl
=> Fix source line reporting at EOF

src/kinds.jl
Several unicode operators were in the wrong precedence category; fix this:
* Assignment, not comparison: `≔` `⩴` `≕`
* Comparison, not plus: `≂`
Also some code movement to reflect precedence and the ordering of unicode codepoints as in the reference parser.
=> Fix operator category/precedence for ≔ ⩴ ≕ ≂

src/parser.jl, src/value_parsing.jl, test/parser.jl
So +0xff is a numeric literal, not `(call-pre + 0xff)`
=> Allow + prefix to be part of unsigned numeric literals

src/expr.jl, test/expr.jl
This "frankenwhere" syntax is used by the SimpleTraits.jl `@traitfn` macro.
=> Fix where parameter conversion as in `A where {X, Y; Z}`

src/expr.jl, src/syntax_tree.jl, test/parser.jl
This makes the tree more symbolic, by using unique SyntaxNode head types to refer to core macro names, rather than needing an explicit reference to the Core module included in the tree.
=> Avoid use of GlobalRef in SyntaxNode trees

test/test_utils.jl, tools/check_all_packages.jl, tools/untar_packages.jl
* Compare Expr in detail against reference parser
* Hack for visual expression diffing
* Cache result of parsing General with reference parser because it's so much slower.
=> Improve registry testing tools

src/expr.jl, src/parser.jl, test/parser.jl
Fix cases where parens are used around module name such as
function (A).f()
end
See in the wild as things like `function ($M).$J() end`
=> Fix an obscure form of function definition

src/parse_stream.jl, src/parser.jl, test/parser.jl
Fixes for `is_eventuall_call` so that the following parse correctly
function (::g(x))() end
function (f::T{g(i)})() end
As part of this, we mark `::` expressions with infix or prefix flags depending on the form to make the two forms easy to detect.
=> Fixes for obscure function definition forms

src/expr.jl, test/expr.jl
Fix Expr conversion for expressions like `x{a, b; i=j}`
Part of #134
=> Fixes for parameters blocks in Expr(:curly)

test/test_utils.jl, tools/check_all_packages.jl
Add special cases to explicitly allow a few incompatibilities for cases where the reference parser has bugs:
* `0x1.8p23f` is a `Float64` literal, with the trailing `f` ignored (also `0x1p1f0`)
* The macrocall in `"@f(a=1) do\nend"` is not the same as the call in `@f(a=1)`
* `global (x,y)` is the same as `global x,y`
* Triple quoted indentation - `"\"\"\"\n  a\n \n  b\"\"\""` parses to "a\n \nb"
Tooling for #134
=> Improve Expr comparison code for registry testing

src/hooks.jl, src/kinds.jl, src/parse_stream.jl, src/parser.jl, src/parser_api.jl, src/tokenize.jl, src/tokenize_utils.jl, test/parser.jl, test/test_utils.jl, test/tokenize.jl
Here we emit invalid token errors during the token validation pass. This ensures any invalid token after parsing is guarenteed to have one single error emitted for it, independent from how it's handled by the parser. Add the special K"Error**" kind to allow us to emit a specific error for the `**` operator.
Ensure we reject all the invalid operators which are rejected by the reference parser including the following which were missing:
* `..+` and similar
* `<---`
Also add an extra rule for parsing invalid binary operators (at some arbitrarily-chosen precedence) to improve the recovered parse tree.
Fix #112 
Part of #172
=> Emit sensible errors for invalid operator tokens

src/parser.jl, test/parser.jl
This syntax is unnecessary but does occur ~10 times in the General registry so we should support it.
Part of #134
=> Allow the syntax `import A.:x` for `import A.x`

src/parser.jl, test/parser.jl
When an interpolation occurs at the beginning of a line without any preceding whitespace this counts as zeroing out the common prefix of indentation.
=> Fix deindentation with triple strings like `"""\n$x a"""`

src/kinds.jl, src/parse_stream.jl, src/tokenize.jl, test/tokenize.jl, tools/check_all_packages.jl
* Improve logging for general registry testing and ignore parser warnings rather than erroring
* Use specific kinds for token errors, not `K"error"`. This fixes a few cases across the General registry where errors should have been reported but were not.
=> Fixes for General registry testing

.github/workflows/CI.yml, Project.toml, src/expr.jl, src/hooks.jl, src/source_files.jl, src/utils.jl, src/value_parsing.jl, test/parse_packages.jl, test/parser_api.jl, test/runtests.jl, test/test_utils.jl, test/value_parsing.jl, tools/check_all_packages.jl
Mostly just compat changes here, adding a bunch of Base utility functions we use which don't exist in earlier Julia versions.
There's still a few failures in the extended tests, probably due to differences in line number node placement and the like in the reference parser.
Fix #180
=> Support for running JuliaSyntax on Julia 1.0

test/expr.jl, test/runtests.jl, test/test_utils.jl
The reference parser sees `(a; b,)` as a block, but the trailing comma implies this should be a frakentuple. Allow this unusual syntax as a minor bug in the reference parser.
Part of #134
=> Allow different parsings of `(a; b,)` to compare equal

src/parser.jl, test/fuzz_test.jl, test/parser.jl
* Line-deletion based fuzzer
* Token-deletion based fuzzer
* Fixes for two crashing bugs found this way
- `"(y::\nif x z end)"`
- `"@(x y)"`
Part of #186
=> More fuzz testing tools and fixes

src/syntax_tree.jl, test/runtests.jl, test/syntax_tree.jl
CC @timholy 
Tim, if there's other API improvements we should have to make the use in https://github.com/JuliaDebug/Cthulhu.jl/pull/345 let's do those too.
=> Allow SyntaxNode `node[end]` to get the last child

src/kinds.jl, src/parser.jl, src/tokenize.jl, src/utils.jl, test/parser.jl, test/tokenize.jl
A fairly big refactor of numeric literal tokenization error cases and a couple of other tokenizer errors ported from the flisp code.
* For hexfloat, emit a more specific errors when the `p` suffix is missing.
* For octal, hex and binary, add errors for trailing invalid digits or identifier characters like `0b123` and `0xenomorph`
* Emit an error for ambiguous numeric constants with dot suffix vs juxtuposition like `1.(`
* Emit an error for underscore directly after dot as in `1._`
* Emit an error for hexfloat without digits `0x.p0`
* Add an invalid operator error for `<---` to follow compatibility with the reference parser.
Refactor and regroup all the numeric tokenization tests which were confusingly grouped.
Fix #57 #172
=> Fix various numeric literal token errors

src/expr.jl, test/expr.jl, test/test_utils.jl
This was incorrect when not including a finally clause.
=> Fix `try catch else` Expr conversion

src/syntax_tree.jl, test/source_files.jl, test/syntax_tree.jl
These two files are particularly affected by recent and upcoming
changes (e.g., #193). This adds a bit more coverage as a guard
against breakage.
=> Improve test coverge of source_files, syntax_tree

src/syntax_tree.jl, test/syntax_tree.jl
Closes #192
Pleasantly straightforward. Note that this object is slightly bigger since `val` has basically become two fields now, one for children and one for the actual value. I hope that's a tolerable increase.
I haven't timed anything to see if there are any regressions. (If constprop works, I think there won't be any.) Is there a task I should use?
=> Split SyntaxNode into TreeNode & SyntaxData

README.md, src/syntax_tree.jl, test/syntax_tree.jl
The byte range is probably most useful for debugging JuliaSyntax than general use. So disable this by default.
=> Remove byte_range from default printing of SyntaxNode

Project.toml
Based on a quick look through the changes I think these are all fixes and generalizations so we should be compatible with 0.3
=> Bump to 0.3.1 and remove old Printf dependency

src/JuliaSyntax.jl, src/precompile.jl
I want to use this package in OhMyREPL but the current latency is too big. This PR makes it as good as Tokenize.jl
Before:
```
julia> @time @eval collect(JuliaSyntax.Tokenize.Lexer("1+1 == 2"))
1.083684 seconds (1.04 M allocations: 63.173 MiB, 0.86% gc time, 99.98% compilation time)
```
After:
```
julia> @time @eval collect(JuliaSyntax.Tokenize.Lexer("1+1 == 2"))
0.016808 seconds (29.64 k allocations: 1.939 MiB, 62.47% compilation
```
cc @timholy
=> add a very basic precompile workload

src/diagnostics.jl, src/parse_stream.jl, src/parser.jl, src/source_files.jl, src/syntax_tree.jl, src/utils.jl, test/diagnostics.jl, test/parser_api.jl, test/runtests.jl, test/source_files.jl, test/syntax_tree.jl, test/test_utils.jl, test/utils.jl
`highlight()` now always prints whole lines of source code, and can highlight arbitrary ranges using box drawing characters, not just with ANSI colors.
Use this to fix diagnostic printing so that it's comprehensible in a non color terminal and so that pasting errors into non-color environments works, as described in https://github.com/JuliaLang/JuliaSyntax.jl/issues/150#issuecomment-1452960722.
The box drawing characters from WGL4 seem like a good balance of:
* Relatively compatible because they're very old, dating from DOS era: https://en.wikipedia.org/wiki/Box-drawing_character#DOS - note we also use these for formatting log messages from Logging.ConsoleLogger.
* Easy to distinguish from the user's source code
I've also found it's helpful to prepend any lines of annotation with a Julia …
=> Rewrite source range `highlight()`

test/test_utils.jl, tools/check_all_packages.jl
Now produces much more readable logs of broken syntax such as
```
┌ Error: Parsers succeed but disagree
│   fpath = "/home/c42f/.julia/dev/JuliaSyntax/tools/pkgs/TropicalYao_0.1.5/src/reversible/LogLikeNumbers/instructs.jl"
│   reduced_chunks =
│    end
│    
│    #          ┌─────────────────────────────────────────────────
│    @i @inline function (:*=(identity))(x::Tropical, y::Tropical)
│        (x |> content) += (y |> content)
│    end
│    #─┘
```
This is on top of https://github.com/JuliaLang/JuliaSyntax.jl/issues/215 - ignore the first commit.
=> Improve syntax diffing in General registry checker

src/expr.jl, src/kinds.jl, src/parser.jl, src/syntax_tree.jl, test/expr.jl, test/parser.jl
With this change `"str" f` now parses as
(doc (string "str") f)
This better represents the surface syntax which isn't an explicit macro call but a juxtaposition at top level.
The lowering to a macro call is done later as part of `Expr` conversion.
Part of #88
=> Parse docstring attachment as `K"doc"` kind

src/expr.jl, src/parse_stream.jl, src/parser.jl, test/parser.jl
Several syntactic constructs can occur either with or without parentheses and it can be useful to distinguish between these without looking at the syntax trivia - particularly for code formatting, but also for other reasons.
* Macro calls: `@x(a,b)` vs `@x a b` (noted in #88)
* Blocks: `(a; b)` vs `begin a ; b end`
* Tuples: `a,b` vs `(a,b)` (for example, see #194)
Also modify the printing of head flags so that each flag is clearly distinguished from every other flag with a `-`.
=> Add PARENS_FLAG to tuple, block and macrocall

src/JuliaSyntax.jl, src/parser_api.jl, src/tokenize.jl, test/fuzz_test.jl, test/parser_api.jl, test/test_utils.jl, test/tokenize.jl
Implement a `tokenize()` function which retreives the tokens *after* parsing.
Going through the parser isn't hugely more expensive than plain tokenization, and allows us to be more precise and complete.
For example it automatically:
* Determines when contextual keywords are keywords, vs identifiers. For example, the `outer` in `outer = 1` is an identifier, but a keyword in `for outer i = 1:10`
* Validates numeric literals (eg, detecting overflow cases like `10e1000` and flagging as errors)
* Splits or combines ambiguous tokens. For example, making the `...` in `import ...A` three separate `.` tokens.
=> Basic after-parse tokenization interface

src/expr.jl, src/parse_stream.jl, src/parser.jl, test/parser.jl, test/parser_api.jl
Introduce a new kind `K"parens"` to represent grouping parentheses with a tree node of their own. This makes it simple for tooling to process and preserve parenthesized expressions without resorting to searching through the attached syntax trivia.
An alternative considered here was to use `K"block"` with a single child which would avoid introducing an extra kind of node. But in that case we couldn't distinguish between a trivial block like `(a;)` vs bare parentheses `(a)`. It also makes implementing `peek_behind` more complicated.
Part of #88. Helps with #22 and #134
=> Enclose grouping parentheses with `parens` node

src/expr.jl, test/expr.jl
This isn't a complete solution, but it improves the situation somewhat. (It's unclear whether we should spend a lot of effort here as converting to Expr is not a particularly expressive path for error propagation. We probably need to plumb diagnostic support into the Julia runtime in a more general way.)
Supersedes #86
=> Better conversion to `Expr` with `parse(..., ignore_errors=true)`

src/diagnostics.jl, src/expr.jl, src/hooks.jl, src/kinds.jl, src/literal_parsing.jl, src/parse_stream.jl, src/parser.jl, src/syntax_tree.jl, test/diagnostics.jl, test/parser.jl
`emit_diagnostic(ps, mark, ...)` now behaves like `emit(ps, mark, ...)` in terms of the source range covered by `mark`. This is much less confusing than the previous behavior.
Also add tests for various diagnostic code paths affected by this.
=> Clean up emit_diagnostic stream position handling

src/expr.jl, src/parser.jl, test/diagnostics.jl, test/expr.jl, test/parser.jl
* Allow parens in import paths like `import A.(:+)`
* Fix parsing of parenthesized macro names in macro calls like `@(A)`
=> Allow parentheses in import paths and macro names

src/expr.jl, src/parser.jl, test/expr.jl, test/parser.jl
* Fix `:kw` conversion in dubious constructs like `f(((a=1)))`
* Fix Expr conversion for parens which contain an error
* Allow more parens in import paths like `import A.:(==)`
=> Various fixes for `K"parens"` nodes

src/literal_parsing.jl
I was trying to use JuliaSyntax is some string benchmarking and noticed a lot of calls to utf8_normalization.
In master `isascii` is now blazing fast, so I thought that checking if a string was ascii before any UTF8 bs would speed things up.  Julia code is mostly ascii
I benchmarked by parsing base/abstractarray.jl which is the largest file in the codebase.
Before pr:
```julia
julia> @benchmark t= JuliaSyntax.parseall(JuliaSyntax.SyntaxNode,$f)
BenchmarkTools.Trial: 291 samples with 1 evaluation.
Range (min … max):  15.019 ms … 25.913 ms  ┊ GC (min … max): 0.00% … 36.31%
Time  (median):     16.389 ms              ┊ GC (median):    0.00%
Time  (mean ± σ):   17.184 ms ±  1.963 ms  ┊ GC (mean ± σ):  4.12% ±  7.50%
▂▂▂█▂
▃▅▆▇▇█████▇▆▅█▄▃▄▁▄▃▄▁▁▂▃▃▁▁▃▁▆▃▃▃▄▁▄▂▃▃▂▃▃▁▁▃▃▁▂▁▁▂▁▁▁▂▁▁▂ ▃
15 ms …
```
=> Add isascii to normalize_identifier for 25% reduction in parse time

src/source_files.jl, test/source_files.jl
Highlighting of empty ranges needs special handling at the ends of lines as the source line of the end of the range can be less than the source line at the start of the range.
=> Fix highlighting of empty source ranges

src/parser.jl, test/parser.jl
Minor fixes for special cases forgotten from #222
=> Add parens node in special cases `:(=)` and `:(::)`

src/expr.jl, src/kinds.jl, src/parser.jl, test/expr.jl, test/parser.jl, test/parser_api.jl
The child layout of try-catch-else-finally is awkward because several of the subclauses are optional. Particularly this has led to problems for `else` in `Expr` which needed to be tacked onto the end for compatibility.
This change clarifies the situation a bit and makes it more future proof by wrapping the subclauses in their own expression heads.
Part of #88
=> Simplify child layout for `try`

README.md, src/JuliaSyntax.jl, src/hooks.jl, src/parser_api.jl, src/source_files.jl, test/benchmark.jl, test/expr.jl, test/parser_api.jl, test/syntax_tree.jl, test/test_utils.jl
`JuliaSyntax.parse()` clashes unfortunately with `Base.parse()`. Choose `parsex` for "parse expression" as a replacement.  Actually I think this might be good anyway, because it's really not clear to me whether `parse()` should parse a single expression or a whole file top-level.  Having a less generic name helps with that I think.
Also add a conservative list of exports that I expect "people are likely to use". There's more to the API than this, but shoving that all into the user's namespace doesn't seem ideal.
=> Conservative exports + rename parse() -> parsex()

src/parse_stream.jl, src/parser.jl, test/parser.jl
This is also distinguishable based on the presence of a child `block` as the only argument, but having the flag is convenient and also allows to distinguish cases like `x.:y` from `x.y`.
=> Distinguish `:x` from `quote x end` with a flag

src/expr.jl, src/parser.jl, test/expr.jl, test/parser.jl
Change the parsing of standalone dotted operators such as `.+` to always parse as `(. +)`, regardless of where they appear syntactically. This removes the last of the cases where operators were coalesced with their leading `.` into a single symbol. For example, `.+(x,y)` is now parsed as `(call (. +) x y)`, rather than `(call .+ x y)`.
The reference parser concatenates the `.` and the operator in some cases, so for compatibility we convert back to that less consistent form during `Expr` conversion.
This addresses the last of the inconsistencies with parsing `.` as discussed in https://github.com/JuliaLang/JuliaSyntax.jl/issues/90.
The last part of #88 (?!?)
=> Parsing standalone dotted operators as `(. op)`

test/fuzz_test.jl, test/parse_packages.jl, test/runtests.jl, test/test_utils.jl, tools/check_all_packages.jl
* Text-based test reduction moved into test_utils
* Remove some obsolete utils
* Rename reduction utils to something more sensible
* List actual reduced failures in package parsing tests
=> Big cleanup of test case reduction utilities

src/parser.jl, test/parser.jl
* Parsing `* <: A` doesn't crash the parser
* `+ <: A` now parses correctly as `(call-pre + (<:-pre A))`.
Fixes part of #186
=> Fix parsing of chained unary and unary type operators

src/parser.jl, test/parser.jl
The tokenizer can't really solve this case, it needs help from the parser. ie, tighter coupling of tokenizer and parser.
However the workarounds here avoid crashing the parser and even gives the right result in most cases.
Close #186. Close #25
=> Avoid crashing on ambiguous tokenization of char vs adjoint

test/expr.jl, test/parser.jl
=> Move all Expr conversion tests to test/expr.jl

src/parse_stream.jl
=> specialize on the number of varargs for `bump_split`

Project.toml, src/expr.jl, src/kinds.jl, src/parse_stream.jl
=> Hot fixes for release 0.3.5

test/test_utils.jl, tools/check_all_packages.jl
* Avoid crash in heuristic Expr comparisons
* reduce_tree(text) returns text not a tree
=> Minor fixes to test tools

README.md, src/expr.jl, src/parser.jl, test/expr.jl, test/parser.jl
This allows `x where T` to be distinguished from `x where {T}` easily which should be quite helpful for source formatting tooling. It's also more consistent with the other allowed (but weird) forms such as `x where {T S}`.
Fixes one of the more interesting cases in #223
=> Add braces node around `T` in `x where {T}`

src/expr.jl, src/green_tree.jl, src/hooks.jl, src/literal_parsing.jl, src/parse_stream.jl, src/precompile.jl, src/syntax_tree.jl, test/benchmark.jl, test/expr.jl, test/parser.jl
Generalize `build_tree` so that we can more easily construct tree types other than `GreenNode`.  Use this to construct `Expr` directly from `ParseStream` rather than constructing both GreenNode and SyntaxNode along the way.
Fix a bunch of type instabilities in the `Expr` conversion code along the way.
With these changes, parsing all of Base to `Expr` is sped up by about 35% overall and allocations reduced by around 50%. (Parsing to `Expr` is now comparable with parsing to `SyntaxNode`.)
=> Construct Expr directly from ParseStream

src/parser_api.jl, src/syntax_tree.jl, test/expr.jl, test/parser.jl
Another approach to fix #239.
Elide all `K"parens"` nodes from the `SyntaxNode` tree, replacing them with their single child.
With #268 merged, this approach works more neatly and doesn't have the downsides of #265.
Close #265
=> Remove `K"parens"` from `SyntaxNode`

src/hooks.jl, test/hooks.jl
This off-by-one error prevented incomplete detection from working for trailing single-character error tokens
=> Small fix for `Expr(:incomplete)` detection

src/expr.jl, src/parse_stream.jl, src/parser.jl, test/expr.jl, test/parser.jl
Copy some peculiar behaviors of the reference parser for compatibility:
* Top level blocks like `a;b;c` don't have any line numbers
* Blocks like `(a;b;c)` omit the first line number node
As part of this, add a new flag `TOPLEVEL_SEMICOLONS_FLAG` to distinguish semicolon-delimited toplevel statements from newline-delimited.
=> Fixes for line number node insertion in short form blocks

src/hooks.jl, test/hooks.jl
When encountering a toplevel error, the reference parser
* truncates the top level expression arg list before that error
* includes the last line number
* appends the error message
Do something similar here so that the associated `LoadError` shows a more reasonable line number.
=> Reference parser compat: Make toplevel error Exprs more compatible

src/parser.jl, test/parser.jl
Expressions like `+(;;)` are ambiguous between parsing as prefix calls with an empty block, vs normal parenthesized calls with multiple parameters:
(call-pre + (block))
(call + (parameters) (parameters))
Fix a few of these cases to use the same somewhat arbitrary disambiguation as the reference parser.
=> Fix for block-vs-parameters in prefix call syntax

src/parser.jl, test/parser.jl
=> Allow `var` identifier as exception name in catch

src/expr.jl, src/parser.jl, test/expr.jl, test/parse_packages.jl, test/runtests.jl, test/test_utils.jl, test/test_utils_tests.jl
* Bump trivia after `=` so we see the correct line for functions in multiple-assignments like `let f(x) =\ng(x)=1\nend`
* Fixes for insertion of these line numbers on the right hand side
* Remove special case avoiding inserting short form function location when in `for` loop iteration spec; allow this in Expr comparison instead.
Part of #270
=> Fixes for short form function locations

src/parse_stream.jl, src/parser.jl, test/parser.jl
Disallow syntax like `"a"begin end`. Add a few more tests for juxtapositon.
Part of #270
=> Disallow juxtaposition of strings with blocks

src/kinds.jl, src/parse_stream.jl, src/tokenize.jl, test/diagnostics.jl
Ported from equivalent errors in the reference parser
Part of #270
=> More precise errors for bad unicode characters

src/precompile.jl
Oops! Accidentally commented out previously.
This bug is pretty bad for latency and exists in the JuliaSyntax-0.4 release :roll_eyes: 
CC @KristofferC in case you get latency bug reports over at OhMyREPL ... Just tell people to update to JuliaSyntax 0.4.1 :grimacing:  I'll release that asap.
=> Re-add precompile

src/kinds.jl, src/parse_stream.jl, src/parser.jl, src/tokenize.jl, test/diagnostics.jl, test/parser.jl, test/test_utils.jl, test/tokenize.jl
Disallow unbalanced Unicode bidirectional formatting directives within strings and comments, to mitigate the "trojan source" vulnerability https://www.trojansource.codes
See also https://github.com/JuliaLang/julia/pull/42918
Fix #242
Closes #270
=> Disallow unbalanced bidirectional unicode

README.md
=> fix typo in readme README.md ?

src/parser_api.jl, test/parser_api.jl
Why this method was there, I don't know!
=> Fix `showerror` to include backtraces

src/hooks.jl, src/parser_api.jl, src/precompile.jl, test/hooks.jl
New hooks added in https://github.com/JuliaLang/julia/pull/46372 allow us to
* Add `JuliaSyntax.ParseError` as the new detail field of `Meta.ParseError`, preserving the detailed error information and ability to overload `showerror`, without disrupting `Base` too much.
* Return `Expr(:incomplete, Meta.ParseError(...))` for incomplete expressions while having `incomplete_tag` still work.
=> Throw Meta.ParseError from Meta.parse() in Julia 1.10

src/parser_api.jl, src/syntax_tree.jl, src/tokenize.jl, test/utils.jl
These were harmless enough, but should satisfy the tests in Base.
Also remove a display_error() overload because (a) it's not designed to be overridden, and (b) this override doesn't really have the intended effect anyway in the latest version where the REPL uses exception stacks more extensively.
=> Minor tweaks to remove method ambiguities and argument ambiguities

src/expr.jl, test/expr.jl
Ensure we add short form function line numbers to the `Expr` when there's a block on the right hand side.
=> Fix for short form function line numbers

src/expr.jl, test/expr.jl
These trailing line numbers are used to attribute coverage to the `end` of the loop for parts of the loop header which run there after lowering.
At least, I think that's what's going on with the fact that coverage changes when using JuliaSyntax in Base.
=> Add trailing line numbers to loops in Expr conversion

test/test_utils.jl, tools/check_all_packages.jl, tools/untar_packages.jl
* Use a separate directory for tar files vs unpacked packages
* Avoid crashing with overlong corrupt symlinks in packages
* When updating the package cache, delete older versions of the same packages.
=> Improvements to General registry test tools

src/expr.jl, test/expr.jl, test/test_utils.jl, test/test_utils_tests.jl
The reference parser accepts this syntax and normalizes it eagerly. So we should do the same rather than making it part of fuzzy Expr comparison later.
=> Normalize `global (x,y)` syntax during `Expr` conversion

src/hooks.jl, test/hooks.jl
The simplest method of doing this is to convert to String, so that's what we do here, using invokelatest.
=> Allow parsing of custom string types in core parser hook

src/parser.jl, test/parser.jl, tools/check_all_packages.jl
Slightly modify the anonymous function arg list disambiguation rules so that the function signature in this syntax parses as
(call (call (quote *=) f))
The package NiLang uses this, so we'd like to keep it working.
Fixes the final niggling case in #134.
See also https://github.com/GiggleLiu/NiLang.jl/issues/83
=> Parse `function (:*=(f))() end` syntax compatibly

docs/src/api.md, prototypes/simple_parser.jl, src/expr.jl, src/hooks.jl, src/kinds.jl, src/literal_parsing.jl, src/parse_stream.jl, src/parser_api.jl, src/precompile.jl, src/source_files.jl, src/syntax_tree.jl, src/utils.jl, test/literal_parsing.jl, test/parser.jl, test/parser_api.jl, test/source_files.jl, test/syntax_tree.jl, test/test_utils.jl
When parsing source code fragments incrementally with
* `Meta.parse(str, index)` or
* `parsestmt(str, index)`
we must avoid scanning the rest of `str` for line numbers for efficiency. In this mode, the user is expected to provide `first_line` to "manually" specify which line number we're counting from.
Admittedly this is a bit clunky and should be integrated better with SourceFile (which should also be renamed - see issue #190) but for now seems to be the most consistent way to approach things here.
Fixes a bug found over at https://github.com/JuliaLang/julia/pull/46372#issuecomment-1593683826
Update: Switching to using `Vector{UInt8}` for literal parsing also makes parsing to `ParseStream` and `GreenNode` around 10% faster
=> Fix line numbers with source fragments

src/diagnostics.jl, src/expr.jl, src/parse_stream.jl, src/parser.jl, src/parser_api.jl, src/source_files.jl, src/syntax_tree.jl, test/hooks.jl, test/source_files.jl, test/syntax_tree.jl, test/test_utils.jl
This fixes a crash formatting error messages when core_parse_hook is used to parse a piece of broken code with a nontrivial byte offset.
* `SourceFile` held by `SyntaxNode` preserves the indexing of the original string passed to the `parse*()` functions.
* Fix `source_line_range` and `thisind` accordingly
=> Fixes for `SourceFile` byte offsets

src/parse_stream.jl, src/parser.jl, src/source_files.jl, test/diagnostics.jl, test/source_files.jl
Diagnostics may sometimes cover trailing text which wasn't consumed. For example, `parseatom(")")` doesn't consume the errant trailing ')', but the diagnostic refers to this character. In this case, `SourceFile` needs to cover the location of the diagnostic in addition to any text which is consumed.
As part of this, mark `sourcetext(::ParseStream)` as deprecated, in favour of constructing a `SourceFile` to wrap things up more neatly.
Also fix a bug in `highlight()` for empty `SourceFile`s.
Fixes #314 and downstream issue https://github.com/JuliaLang/julia/issues/50245
=> Fix diagnostics covering trailing text

src/expr.jl, test/expr.jl
=> Fix parse error with broken do syntax

docs/src/reference.md, src/expr.jl, src/parser.jl, test/expr.jl, test/parser.jl
`do` syntax is represented in `Expr` with the `do` outside the call. This makes some sense syntactically (do appears as "an operator" after the function call).
However semantically this nesting is awkward because the lambda represented by the do block is passed to the call. This same problem occurs for the macro form `@f(x) do \n body end` where the macro expander needs a special rule to expand nestings of the form `Expr(:do, Expr(:macrocall ...), ...)`, rearranging the expression which are passed to this macro call rather than passing the expressions up the tree.
In this PR, we change the parsing of
@f(x, y) do a, b\n body\n end
f(x, y) do a, b\n body\n end
to tack the `do` onto the end of the call argument list:
(macrocall @f x y (do (tuple a b) body))
(call f x y (do (tuple a b) body)) …
=> AST: Rearrange `do` to sit inside `call`/`macrocall`

docs/src/design.md
The code block has to be indented at the same level as the list elements, otherwise Documenter won't parse it correctly.
=> Fix code block indentation

src/source_files.jl
For example, without this, iteration over `.code` yields `AbstracChar`s rather than `Char`s.
=> Make `SourceFile.code` infer concretely

src/parse_stream.jl, src/parser.jl
=> Remove `num_tokens` argument from `bump_glue`

src/parser_api.jl, test/parser_api.jl
Parser recovery commonly results in several errors which refer to much the same location in the broken source file and are not useful to the user.
Currently the most useful error is the first one, so this PR trims down error printing to only show that one.
Fixes https://github.com/JuliaLang/julia/issues/50223
=> Only show the first parse error

src/expr.jl, src/parser.jl, test/expr.jl
=> Fix SyntaxNode->Expr conversions of unterminated cmd strings

src/hooks.jl
Adds "This is probably not your fault, please submit a bug report (https://github.com/JuliaLang/JuliaSyntax.jl/issues)" to the long message when JuliaSytnax has an internal bug.
```
julia> map([3,4,5])[1] do x
┌ Error: JuliaSyntax parser failed — falling back to flisp!
│ This is probably not your fault, please submit a bug report (https://github.com/JuliaLang/JuliaSyntax.jl/issues)
│   exception =
│    Internal error: length(args) == 3
│    Stacktrace:
│      [1] error(::String, ::String)
│        @ Base ./error.jl:44
│      [2] internal_error(strs::String)
│        @ Base.JuliaSyntax /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-R17H3W25T9.0/build/default-honeycrisp-R17H3W25T9-0/julialang/julia-release-1-dot-10/base/JuliaSyntax/src/u …
```
=> Add a "not your fault" hint to the fallback to flisp error

src/parser.jl, test/parser.jl
Consume the trailing ' in empty characters '' for better error recovery when `ignore_errors=true` is set.
=> Better recovery when parsing empty characters

src/expr.jl, src/literal_parsing.jl, src/parse_stream.jl, src/parser.jl, src/syntax_tree.jl, test/expr.jl, test/parser.jl, test/test_utils.jl
Cleanup weird cases where the parser would `bump()` interior nodes into the output stream rather than `emit()`ing them. Emitting all interior nodes explicitly means we can remove some special cases which occurred during tree building.
As part of this, fix some errors converting broken expressions like `x var"y"` from `SyntaxNode` to `Expr`.
Fixes #330
=> Always `emit()` nodes with zero children, don't `bump()` them

src/diagnostics.jl, test/diagnostics.jl
Computing the file URL for pretty printing using `abspath` can fail when the current working directory doesn't exist. This is a quick fix for this issue (which is incredibly confusing/disruptive if the user does manage to enter a nonexistant working directory!)
A more complete fix would avoid ever looking at the working directory when printing diagnostics, instead requiring the caller to pass in a richer definition of the "location of source code" than the mere file name as a string. However getting something sensible working there is (a) breaking and (b) unclear on may details. So just patching this up quickly seems good for now.
Fix #359
=> Fix diagnostics printing when `pwd()` doesn't exist

src/expr.jl, test/expr.jl
Fix #341
The root issue was the unconditional conversion of an `Expr(:dotcall, foo, ...)` to `Expr(:call, Symbol(:., foo), ...)` when `foo` was not an `Expr(:., ...)`. That case corresponds to dotted operators (where `foo` is the symbol of the operator), but it can actually also occur when there is a parsing error, such as misplacing a non-unitary dotted operator like in the MWE.
I'm not completely sure what `Expr` should be yielded here, I went for `Expr(:dotcall, Expr(:error, Expr(:., foo), ...)` because it required minimal change, but let me know if it should be something else!
=> Fix Expr conversion of erroneous operator dot call

Project.toml, test/diagnostics.jl, test/fuzz_test.jl, test/test_utils.jl
This rearrangement allows us to fuzz test the hooks (which use the low level parser API) as well as the high level parser API.
We've had various cases of bugs in the hook system which aren't reflected in the high level parser API. Fuzz testing more of the system is one way to catch some of these bugs.
=> Generalize fuzz testing tools

src/parser.jl, test/parser.jl
=> Fix crash with empty macro name when parsing `"@("`

src/hooks.jl, test/fuzz_test.jl, test/hooks.jl
Fixes part of  #380
(This may have crept in as part of #325?)
=> Fix error in hooks when parsing incomplete `x.`

src/parser.jl, test/parser.jl
Ensure that we never treat things like `"mutable\nstruct"` as introducing a mutable struct definition, even within parentheses where newline whitespace is insignificant.
Fixes part of #380
=> Disallow newline between contextual keyword pairs in parentheses

src/parser.jl, test/fuzz_test.jl, test/parser.jl
When word operators are parsed as atoms (ie, identifiers), the kind should be remapped as such. This fixes a crash when parsing `function(where` because `was_eventually_call` assumes that a kind of `K"where"` implies an internal node.
Part of #380
=> Fix crash when parsing malformed `function(where`

src/parser.jl, test/parser.jl
In expressions like `"a +\n\n<:"` the presence of `peek(ps, skip_newlines=true)` was inconsistent with the use of `bump()` without `skip_newlines`. It seems that we didn't need skip_newlines at all in parse_unary_subtype, so do this to be consistent with parsing of other operators.
Fix #392
=> Fix bug parsing unary subtypes with newlines

src/parser.jl, test/parser.jl
There are some lexing ambituities in primes vs cmd delimiters. We break these with a simple rule in the lexer but there's edge cases of invalid or extremely strange syntax where this can be inconsistent with the parser. The following were some such cases which caused an assertion error in the parser.
"var\"#\"``\$"
"x in'``\$"
This change avoids crashing in those cases, emitting an error instead.
See also #25
Fix part of #380
=> Fix crashes due to lexing ambiguity of string delimiters

src/parser.jl, test/diagnostics.jl, test/hooks.jl
When a missing closing token like `)`, `]` or `}` is encountered we want the "Expected `)`" error to point to a location one past the last valid token, not to the trailing error tokens.
For example from #349 here's a poor error message from the existing code:
ERROR: ParseError:
ylims!(p, (0, last(ylims(p)))
xlabel!(p, "Contig length cutoff (kbp)")
After this change, the error location instead points to the end of the last valid line:
ERROR: ParseError:
ylims!(p, (0, last(ylims(p)))
Fix #349, fix #313
=> Improve error message for missing closing tokens

src/parse_stream.jl
When looking at the help for `peek` in the repl, the current docstring looks like it applies to all `IO`, so I added `::ParseStream` to make the docstring more specific. See also https://github.com/JuliaLang/julia/issues/54749
=> Update `Base.peek` docstring

test/parse_packages.jl
Implements the short-term solution in #446, intented to fix #444 and implements step one in #395
=> Fix corpus tests on Julia 1.10+

.github/workflows/CI.yml
- 1.9 is no longer 1
- pre is now available (see https://github.com/julia-actions/setup-julia?tab=readme-ov-file#examples)
Updates test config to conform to @davidanthoff's suggestion from #444, but does not fix broken 1.10 and 1.11.0-rc tests.
=> Run CI on 1.9 and prerelease

Project.toml, src/green_tree.jl, src/kinds.jl, src/source_files.jl, src/syntax_tree.jl, test/runtests.jl, test/serialization.jl
I need these helper functions to facilitate checking if a string parses the same way on different versions of JuliaSyntax. They're generally useful/bugfixes/implement missing functionality that should be expected, so I figure I'll include them in `src`.
Fixes #449 - a hash-== mismatch bug
Implements #450 - supports equality on `SyntaxNode`
Implements #451 - supports serialization by implementing `read` and `write` on `Kind`. I used strings instead of UInt16 to represent Kind, see inline comment for more info.
=> Hashing fixup, equality support, and serialization support

.github/workflows/CI.yml
Follow existing pattern and only run CI on 1.9 on ubuntu 64 bit.
Fixup for  #445
=> Cut back on CI on 1.9

src/tokenize.jl, test/tokenize.jl
Before this patch the `\r` character would be part of the comment and not the following NewlineWs (which would simply be a `\n`-style NewlineWs instead of a `\r\n` as one would expect).
=> Fix emitting comments followed by `\r\n`

src/parser.jl, test/parser.jl
This syntax is normally not something you'd use, but it's very useful for `ccall`. Previously the parser just crashed on this kind of input - a bug which is also present in the old parser.
=> Fix parsing of `-1::Int` - signed literals with type assertions

src/tokenize.jl, test/tokenize.jl
Without this patch `\r\n\r\n` would be tokenized as `\r\n\r` and `\n` instead of `\r\n` and `\r\n`. Fixes
https://github.com/fredrikekre/Runic.jl/issues/15.
=> Fix tokenization of consecutive `\r\n` line endings

src/syntax_tree.jl
This is a useful generic function to compliment `children()` in the case that `children()` is slightly nontrivial, for example in implementing `JuliaLowering.SyntaxTree`
=> Define `numchildren()` function

src/kinds.jl, test/kinds.jl, test/runtests.jl
Extensible kinds are quite tricky. We want
* To use a small number of bits for them
* To have the string representation in the source, but have the compiler able to fully inline the integer representation.
* Allow modules with different kinds to cooperate together on the same integer representation.
* Not trigger invalidation when new kinds are added
* Different `Kind` modules to not require cooperation
This is a very hard set of constraints to satisfy. The last one is already impossible in a single flat namespace so in this design we've given up on it and require cooperation between all kind extension modules, including module authors allocating non-colliding id's for their modules, in addition to non-colliding kind names.
Why do we need this?  It's very convenient for JuliaLowering to …
=> Allow `Kind`s to be registered by packages outside JuliaSyntax

docs/src/api.md, src/diagnostics.jl, src/expr.jl, src/syntax_tree.jl, tools/check_all_packages.jl
This overload was a mistake - it doesn't really have the same semantics as compared to `Base.range()`
Fixes #417
=> Move overload of Base.range() to JuliaSyntax.byte_range()

.github/workflows/CI.yml
Remove cache artifacts step from test CI because JuliaSyntax does not use artifacts in its test pipeline
=> Cleanup CI

Project.toml
Xref https://github.com/JuliaLang/JuliaSyntax.jl/pull/460#issuecomment-2234393983. It is quite confusing right now that the version on main is lower than released versions.
=> Set version on main branch to 1.0.0-DEV.

src/expr.jl, src/source_files.jl, src/syntax_tree.jl
* Having a generic version of this is useful for other syntax tree types such as `JuliaLowering.SyntaxTree`
* Function to get the `SourceFile` for a syntax object
* Generic `highlight()` implementation in terms of this
=> Generic `sourcefile()` function

.github/workflows/CI.yml, Project.toml, src/parse_stream.jl, src/parser.jl, src/tokenize.jl, test/parse_packages.jl, test/parser.jl, test/tokenize.jl
I am sure there are more fixes to backport but these are the ones I care about right now. If I, or someone else, needs other fixes we can release 0.4.10 with more backports.
=> Backport release 0.4

docs/src/api.md, src/diagnostics.jl, src/expr.jl, src/parse_stream.jl, src/parser_api.jl, src/source_files.jl, src/syntax_tree.jl, test/hooks.jl, test/test_utils.jl
* Move all source code access functions which refer to source locations and strings into the top of source_files.jl, and add some documentation for these.
* Add `filename()` function to determine source file name of a syntax object
* Also add a minor generalization to SyntaxNode->Expr conversion code to make Expr conversion general enough to allow it to also be used for JuliaLowering.SyntaxTree. (internal/experimental interface, for now)
=> Cleanup/document source code access functions + add `filename()`

docs/src/api.md, src/parse_stream.jl
@davidanthoff @domluna I hope this helps answer some questions about how to work with expressions kinds and flags.
=> Add a pile of documentation for expression predicates

src/tokenize.jl
I was testing [ExplicitImports.jl](https://github.com/ericphanson/ExplicitImports.jl) and noticed this unnecessary import:
````julia
julia> using JuliaSyntax, ExplicitImports
julia> print_explicit_imports(JuliaSyntax)
Module JuliaSyntax is not relying on any implicit imports.
Module JuliaSyntax.Tokenize is not relying on any implicit imports.
Additionally JuliaSyntax.Tokenize has stale explicit imports for these unused names:
JuliaSyntax
is_error
````
I left the `JuliaSyntax` one since I figured it could be annoying if you are working in that module and the name is unexpectedly unavailable. I feel that removing the `is_error` one improves clarity though, as it makes it easier to see that Tokenize does not add a method for `is_error` (or even use it).
=> Remove unused `is_error` import in Tokenize module

src/parser_api.jl, test/hooks.jl, test/parser_api.jl
I totally missed that the `(..)` issue from #350 was a warning rather than an error; I think probably bc the bold red part says `ERROR: ParseError:` and then the very light part says "Warning". Here I propose add to text to make it clearer by emphasizing warning vs error on the first line.
=> add "some warnings detected" to ParseError printing when all problems are warnings

docs/src/reference.md, src/expr.jl, src/kinds.jl, src/parser.jl, test/parser.jl
I got inspired to implement #432 as suggested there... This should be a complete implementation of that proposed solution, but may still need experimentation/thought to decide whether Cartesian iteration should be nested or flat.
---
The `=` node which has traditionally been used for iteration specifications in `for` loops and generators doesn't have normal assignment semantics. Let's consider
for x in xs
body
end
which has been parsed as `(for (= x xs) (block body))`.
Problems:
* The iteration does create a binding for `x`, but not to the expression on the right hand side of the `=`.
* The user may use `in` or `∈` in the source code rather than `=`. The parser still uses a `=` node for consistency but this only emphasizes that there's something a bit weird going on.
So this use of `=` is …
=> Change AST for iterations to use `iteration` kind

docs/src/api.md, src/expr.jl, src/parse_stream.jl, src/parser.jl, test/parse_packages.jl, test/parse_stream.jl, test/parser.jl, test/test_utils.jl
Fix #465 - see rationale there.
Fixing this turned out to be quite easy.
Compat:
* This is a breaking change to the JuliaSyntax AST
* Non-breaking for `Expr`
=> Use `K"function"` for short form function AST

src/parser.jl, test/diagnostics.jl, test/parser.jl
=> Make `using :A` an error; fix `using A: (..)` warning

src/kinds.jl, src/parser.jl, test/parser.jl
These assignment-precedence operators shouldn't be special syntax and should instead be usable as normal identifiers just like `~`.
Fix #405
=> Allow any of `≔ ⩴ ≕` as identifiers

docs/src/reference.md
Doc fixes related to #466 and #432
=> Fixes for AST reference documentation

src/expr.jl, test/expr.jl, test/parser.jl
Found when running the downstream tests in Base
=> Fix bug converting cmd string macros to Expr

src/expr.jl, src/green_tree.jl, src/hooks.jl, src/syntax_tree.jl, test/green_node.jl, test/test_utils.jl
Unfortunately, `haschildren(x)` was a terrible name because it's not testing the same thing as `numchildren(x) == 0`!
In our ASTs
* Leaves of the tree correspond to tokens in the source text
* Internal nodes are containers for a range of tokens or other internal nodes.
Occasionally we can have internal nodes which have no tokens and thus have `numchildren(node) == 0`. These are, however, still "internal nodes" and we have `haschildren(node) === true` for these which makes no sense!
=> Rename `haschildren()` to `is_leaf()`

tools/bump_in_Base.jl
It turns out that this is basically a local version of BumpStdlibs.jl. But I've typically found the need to test Julia locally before making the PR, so here's the script fwiw.
=> Tool to bump JuliaSyntax version in Base

docs/src/api.md, src/JuliaSyntax.jl, src/source_files.jl, test/syntax_tree.jl, test/test_utils.jl
=> Implement `char_range()` to respect string indices

src/expr.jl, src/kinds.jl, src/literal_parsing.jl, src/parser.jl, src/syntax_tree.jl, src/tokenize.jl, test/parser.jl, test/tokenize.jl
Use a single `K"Bool"` Kind for booleans. This is both more convenient and more consistent with other literal kinds such as K"Integer" which group all integers under a single kind.
Replace the use of the invisible `K"false"` token in catch blocks with a new kind `K"Placeholder"` - this removes the last of the invisible tokens, other than error tokens! K"Placeholder" will also be really useful for JuliaLowering as a kind for all-underscore identifiers.
=> Replace K"true" and K"false" with K"Bool"

src/syntax_tree.jl, test/syntax_tree.jl
The leaf kind is fairly critical information - this change ensures it's shown by default when printing syntax trees.
Conversely, the byte offset and line/column is generally not very useful, so hide this by default.
=> Show leaf Kinds when printing syntax trees

src/parser.jl, src/utils.jl
Allows the example in https://github.com/JuliaLang/JuliaSyntax.jl/issues/490 to compile (together with https://github.com/JuliaLang/julia/pull/55047#issuecomment-2277844004).
=> add some small type inference improvements to allow for some basic static compiling

docs/src/api.md, src/JuliaSyntax.jl, src/green_tree.jl, src/hooks.jl, src/syntax_tree.jl, test/green_node.jl, test/runtests.jl, test/syntax_tree.jl, test/test_utils.jl
Here I commit to a more consistent but simpler child access API for syntax trees, as informed by the JuliaLowering work so far:
* `is_leaf(node)` is given a precise definition (previously `!haschildren()` - but that had issues - see #483)
* `children(node)` returns the child list, or `nothing` if there are no children. The `nothing` might be seen as inconvenient, but mapping across the children of a leaf node is probably an error and one should probably branch on `is_leaf` first.
* `numchildren(node)` is documented
* `node[i]`, `node[i:j]` are documented to index into the child list
We distinguish `GreenNode` and its implementation of `span` from `SyntaxNode` and its implementation of `byte_range` and `sourcetext` - these seem to just have very different APIs, at least as of now.
I've …
=> Clean up and document syntax tree child access API + mark public API

src/parser.jl, test/expr.jl
=> Consistent attachment of syntax trivia to top level statements

src/hooks.jl, test/hooks.jl
=> Terminate :statement parsing at newlines

src/parser.jl, test/parser.jl
Disallow generator syntax with trailing non-delimited expressions
(y for x in xs a)
(y for x in xs a, b)
Allow parameter syntax such as
f(y for x in xs; a)
because the flisp parser allowed this it's used in Base in at least one location.
Disallow the almost-equivalent block syntax for now:
(y for x in xs; a)
because the flisp parser disallowed it and users can always get the same thing with some extra parentheses.
Fixes #407
=> Disallow trailing junk in generators

src/kinds.jl, test/serialization.jl
This patch fixes serialization of `Kind`s to use `sizeof` (number of bytes) instead of `length` (number of characters) when computing number of bytes in the stringified `Kind`.
=> Fix serialization of kinds with multibyte chars

README.md
self descriptive
.svg file not rendering on WiFi networks enforcing https
=> https in readme

src/expr.jl, src/parser.jl, test/expr.jl, test/parser.jl
Julia's ecosystem (including Base.Docs and flisp lowering) assumes that strings within `struct` definitions are per-field docstrings, but the flisp parser doesn't handle these - they are only recognized when the struct itself has a docstring and are processed by the `@doc` macro recursing into the struct's internals. For example, the following doesn't result in any docs attached to `A`.
```julia
struct A
"x_docs"
x
"y_docs"
y
end
```
This change adds `K"doc"` node parsing to the insides of a struct, making the semantics clearer in the parser tree and making it possible to address this problems in the future within JuliaLowering.
Also ensure that the `Expr` form is unaffected by this change.
=> Parse docstrings within structs as `K"doc"`

Project.toml, src/parse_stream.jl, test/parse_stream.jl
- Still assume `Substring{String}` has `pointer`
- Add tests
Fixes #505
=> Don't assume that `SubString` has `pointer` and copy instead

src/hooks.jl, test/hooks.jl
Previously we relied on the last SyntaxNode consuming all trailing whitespace when detecting incomplete syntax. However this assumption was broken by #397 and is generally fragile with respect to any extra bump_trivia() calls. Fix this by just comparing to the stream position before any bumping of remaining trivia.
Should fix #512
=> Fix `incomplete_tag` generation with trailing whitespace

docs/src/api.md, src/parse_stream.jl, src/parser.jl, test/parser.jl
This syntax flag allows the stylistic choice of adding trailing commas to be easily detected. For example, `f(x)` vs `f(x,)` and `(a,b)` vs `(a,b,)`.
=> Add `TRAILING_COMMA_FLAG` to distinguish `(a,b)` vs `(a,b,)`

docs/src/reference.md, src/expr.jl, src/parser.jl, test/expr.jl, test/parser.jl
This makes argument lists on the left hand side of `->` parse as tuples. In particular, this fixes a very inconsistent case where the left hand side previously parsed as a `K"block"`; we now have:
* `(a;x=1)->b` ==> `(-> (tuple-p a (parameters (= x 1))) b`
rather than `(block a (= x 1))` on the left hand side.
In addition, the following forms are treated consistently
* `a->b`       ==> `(-> (tuple a) b)`
* `(a)->b`     ==> `(-> (tuple-p a) b)`
* `(a,)->b`    ==> `(-> (tuple-p-, a) b)`
The upside of this is that expression processing of `->` syntax should be much easier.
There's one aberrant case involving `where` which is particularly difficult and still not dealt with:
`(x where T) -> b` does not parse as `(where (tuple x) T)` on the left hand side. However, `where` precedence involving …
=> Make left hand side of `->` parse as a tuple of arguments

src/expr.jl, src/kinds.jl, src/parse_stream.jl, src/parser.jl, src/parser_api.jl, test/green_node.jl, test/parser.jl, test/parser_api.jl, test/syntax_tree.jl
Most operators are semantically just normal identifiers after parsing so should get the Kind `K"Identifier"`. For example, after this change `a + b` parses with `K"Identifier"` kind for the `+` token.
As an exception, standalone syntactic ops keep their kind - they can't really be used in a sane way as identifiers or interpolated into expressions in the normal way because they have their own syntactic forms. This also helps us in `Expr` conversion where they also have their own rules for coalescing with dots, when dotted.
Also introduce a new keyword `operators_as_identifiers` to the `tokenize()` API to accommodate some simple uses of this API to colour token strings by operator type, even when the operator is semantically in identifier-position.
Fix #474 as a follow-on from #456
CC …
=> Parse non-syntactic operator tokens as `K"Identifier"` kind

src/kinds.jl, src/tokenize.jl, test/tokenize.jl
The character U+1F8B2 🢲 (RIGHTWARDS ARROW WITH LOWER HOOK) is new is Unicode 16; it is of a kind (no pun intended) with the longstanding characters U+21A9 ↩ (LEFTWARDS ARROW WITH HOOK) and U+21AA ↪ (RIGHTWARDS ARROW WITH HOOK), both of which are already supported as operators in Julia.  If more evidence of its worth is needed, it was added to Unicode as part of the Symbols for Legacy Computing effort, wherein it was sourced from Smalltalk character sets in the 1970s—so it has a very long history of being used in programming languages!
=> Add U+1F8B2 🢲 as an operator

src/parser.jl, test/parser.jl
Quick fix for https://github.com/JuliaLang/julia/issues/57223
This bug was brought on by the parsing change in #522.  Basically, we can't reliably look ahead at the `K"->"` token when parsing parentheses in `parse_paren()` if any construct with higher precedence is currently being parsed on the left hand side of the `$`.  Luckily there's very few such constructs, but `$` is one of these.
The others appear to be unary `&` and unary `::` which are also entangled in `where` parsing so are a bit more difficult to fix. Thus the obscure and probably useless syntaxes `::(x) -> y` and `&(x) -> y` are currently broken.
In principle, a way to fix this at the correct precedence level would be to rewrite the left hand side of `->` when bumping the `K"->"` token itself, and when the left hand side was …
=> Avoid adding tuple in parsing of `$(x) -> rhs`

src/hooks.jl, src/parse_stream.jl, test/hooks.jl
Rework incomplete expression detection so that trailing whitespace is always ignored, regardless of how the parser itself decides to attach it to other nodes of the tree.
To do this, we walk back from the end of the parse stream and look for the byte offset of the last non-whitespace token. We then use that to determine whether the error node is "at the end of the parse".
Improve testing by
* Extracting the incomplete expressions which are part of the REPL stdlib tests and ensuring these match the incomplete tag generation of the flisp parser. Fix some divergences for `var""` syntax and invalid escape sequences in strings.
* Ensuring that we test both `:statement` and `:all` level parsing - the REPL uses `:all` to allow parsing of multiple top level statements, so we need to test this. …
=> Make `Expr(:incomplete)` detection more robust to whitespace

.github/workflows/CI.yml
GitHub yanked cahce@v1 (caused all jobs that use it to fail). This breaks our CI. This bump should fix it.
=> Update cache version to unbreak CI

src/precompile.jl
This has to be compiled now in the REPL otherwise:
```
precompile(Tuple{typeof(Base.JuliaSyntax.core_parser_hook), Base.SubString{String}, String, Int64, Int64, Symbol})
```
=> also precompile for `SubString`

src/tokenize.jl
avoids github.com/JuliaLang/julia/issues/33712, matches https://github.com/JuliaLang/Tokenize.jl/pull/213
probably rarely makes a difference but might as well; this should be strictly better.
=> simple_hash faster by lifting length(str)

src/source_files.jl, test/source_files.jl, test/syntax_tree.jl
When constructing SourceFile's `line_starts`, we currently pretend there's a
newline at the end of the source if there isn't one, and then ignore the last
newline unconditionally.  This became a problem in LSP testing, where calling
`source_location` with a cursor position at the end of the file would give a
wrong result only if the last character was a newline.
```
julia> source_location(SourceFile("\n\n\n"), 1)
(1, 1)
julia> source_location(SourceFile("\n\n\n"), 2)
(2, 1)
julia> source_location(SourceFile("\n\n\n"), 3)
(3, 1)
julia> source_location(SourceFile("\n\n\n"), 4)
(3, 2)
```
This change removes the conditional line and the code stripping it.  This also
brings `line_starts` closer to its definition (one entry per line in the file).
Alternatively, we could add the dummy line …
=> Make `source_location()` and SourceFile's and `line_starts` consistent when the last source byte is a newline

src/expr.jl, src/hooks.jl, src/syntax_tree.jl
This will allow for automatic hookup to be done via `InteractiveUtils.@activate JuliaSyntax`. 
TODO: On julia's end, we'll need to add JuliaSyntax to the components we're allowed to activate (and bump the JuliaSyntax version).
=> add `activate!` function as alias to `enable_in_core!`

src/expr.jl, src/kinds.jl
`inert` is mostly used in lowering. As far as I can tell, there is precisely one place in the flisp parser that produces it:
https://github.com/JuliaLang/julia/blob/d6b3669621ceb18aea693d8544b2c38870d289ad/src/julia-parser.scm#L1259
However, we do not insert and `inert` there in JuliaSyntax, instead preferring to automatically quote the rhs of a `.` head in expr conversion:
https://github.com/JuliaLang/JuliaSyntax.jl/blob/eceaa39706c6ecc3ef496613096216625dba558e/src/expr.jl#L310
As a result, (and as code coverage complains),  the syntax head is unused and should be removed here. However, it should probably then be added back in JuliaLowering.
=> kinds: rm unused kind K"inert"

src/expr.jl, src/hooks.jl, src/tree_cursors.jl
This builds on top of #560 and replaces the use of `SyntaxNode` in hooks.jl by the new lower-level cursor APIs. This avoid allocating two completely separate representations of the syntax tree.
As a result, the end-to-end parse time for error-containing code is between 1.5x (if the error is the first token) and 2x (if the error is the last token) faster than current master. However, the main motivation here is just to reduce coupling between the Expr-producing and SyntaxNode producing parts of the code.
=> Use implicit tree for error search

src/core/parse_stream.jl, test/hooks.jl
to ensure that `let x = 1 # comment` is treated as an incomplete expression.
Fixes https://github.com/JuliaLang/JuliaSyntax.jl/issues/565.
=> fix: skip zero-width error tokens in last_non_whitespace_byte

LICENSE.md, src/core/parse_stream.jl, src/integration/expr.jl, src/julia/julia_parse_stream.jl, src/julia/kinds.jl, src/julia/parser.jl, src/julia/tokenize.jl, test/diagnostics.jl, test/parser.jl, test/tokenize.jl
This implements the first of a series of AST format changes described in #567. In particular, this removes the DOTOP_FLAG. Currently, we already do not emit the DOTOP_FLAG on terminals, they always get split into one dot token and one identifier token (although we did set it on the intermediate tokens that came out of the lexer). The only four kinds for which DOTOP_FLAG was ever set in the final AST were `=`, `op=`, `&&` and `||`. This introduces separate head kinds for each of these (similar to how there are already separate head calls for `dotcall` and `dot). Otherwise the AST structure should be unchanged.
=> Remove DOTOP_FLAG from tokenizer and parser

src/integration/expr.jl
Two small and related changes:
1. The node->expr conversion shouldn't peek at provenance from SyntaxNode or SyntaxTree, so fix the couple of places we do this.  We've always had provenance available, but we won't once there are nodes constructed from exprs for compatibility.
2. JuliaLowering currently relies on putting its own data structures through the JuliaSyntax node->expr machine.  Remove a couple of type annotations and reinstate `_expr_leaf_val` so that this is possible.
This change should make JuliaSyntax compatible with JuliaLowering again after #560, though some tweaks need to be done on JuliaLowering's end before JETLS can bump deps (cc @aviatesk)
=> Tweaks to expr-conversion for JuliaLowering

src/integration/expr.jl, src/julia/kinds.jl, src/julia/literal_parsing.jl, src/julia/parser.jl, src/julia/tokenize.jl, test/diagnostics.jl, test/expr.jl, test/green_node.jl, test/parser.jl
The current representation for macro names is a bit peculiar. When the parser encounters `@a`, it treats `@` as notation for the macrocall and then `reset_node!`'s (which itself may be considerd a bit of a code smell) the `a` to a special MacroName token kind that (when translated back to julia Expr) implicitly adds back the `@`. Things get even more preculiar with `@var"a"` where only the token inside the string macro gets reset.
One particular consequence of this is https://github.com/JuliaLang/julia/issues/58885, because our translation back to Expr does not check the RAW_STRING_FLAG (whereas the translation for K"Identifier" does).
A second issue is that we currently parse `@A.b.c` and `A.b.@c` to the same SyntaxTree (of course the green tree is different). We aren't currently being …
=> Tweak macro name representation

src/integration/expr.jl, src/porcelain/green_node.jl, src/porcelain/syntax_tree.jl
Currently `build_tree` accepts extra `kwargs...` which causes actually invalid `kwargs...` to be silently ignored. This is particularly confusing since they can be mixed up with `_parse!` keyword arguments. This change clarifies which keyword arguments `build_tree` accepts and makes it explicitly error when invalid keyword arguments are passed.
=> build_tree: clarify accepted keyword arguments

src/julia/kinds.jl
The variable `i` was unintentionally shared between the generator closure in `_register_kinds!` and another part of the body of `_register_kinds!`. Thus `i` was boxed, causing trouble for inference.
Fix this by moving the part of `_register_kinds!` with `i` to a new function.
Fixing this should make the sysimage more resistant to invalidation, once the change propagates to Julia itself.
=> `_register_kinds!`: prevent unintentional closure capture, boxing

src/kinds.jl
The variable `i` was unintentionally shared between the generator closure in `_register_kinds!` and another part of the body of `_register_kinds!`. Thus `i` was boxed, causing trouble for inference.
Fix this by moving the part of `_register_kinds!` with `i` to a new function.
Fixing this should make the sysimage more resistant to invalidation, once the change propagates to Julia itself.
xref:
* the PR being backported: #586
* backport release PR #577
=> backport to v1: `_register_kinds!`: prevent unintentional closure capture, boxing
